# This file was generated by GoReleaser. DO NOT EDIT.
cask "logbro" do
  name "logbro"
  desc "Log viewer for stdin logs"
  homepage "https://github.com/lch88/logbro"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logbro"

  on_macos do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.2.7",
        ]
      sha256 "63f2d7a00abc185c06d93962b99e223069e1c8c0ce149ffc8ada3a2007e81ea6"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.2.7",
        ]
      sha256 "30876519a6a58f55dc81bcaf08a41bfc2b9dbfeaa960c79d5a44fb1699e8cc8c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.2.7",
        ]
      sha256 "b060516bb05f72cc26288e279adc28a73cb33bae1ce967dd447ffc6b13b40562"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.2.7",
        ]
      sha256 "d6daab136de58b66b6283c36f409c00d86f16df02e18234090f7c6a2d89958a4"
    end
  end

  # No zap stanza required
end
