# This file was generated by GoReleaser. DO NOT EDIT.
cask "logbro" do
  name "logbro"
  desc "Log viewer for stdin logs"
  homepage "https://github.com/lch88/logbro"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logbro"

  on_macos do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "8abff4e2100123b659ca3d9e02f3d04a043432182d4d33c812be51d5338aca42"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "dd028608dd0cc3883212cf765fd9055cf6f33a41ba1bd879b6bf3bcd96328e0e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "c1542d3d187545d61d525116afc0732b2539cde9a57071be523353231d37f629"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.0.6",
        ]
      sha256 "63a6010f43c6ac3f05f715c0e326fb50a59652342557b47f0fbb8c57a51cf68b"
    end
  end

  # No zap stanza required
end
