# This file was generated by GoReleaser. DO NOT EDIT.
cask "logbro" do
  name "logbro"
  desc "Log viewer for stdin logs"
  homepage "https://github.com/lch88/logbro"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logbro"

  on_macos do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.0",
        ]
      sha256 "56556f6d28e736b42fe3ae24bd0e85a551ded29eecdbb11da95cb0c0b35daa1d"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Darwin_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.0",
        ]
      sha256 "4a714c0b5f6b01c5ab614a7d6136e98780e796cd68f0cf1a684de0a60a57e15e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_x86_64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.0",
        ]
      sha256 "cae1363a884d3e00b56a92a766d488ff6a2f502c13711f0ee2f6344c69450e24"
    end
    on_arm do
      url "https://github.com/lch88/logbro/releases/download/v#{version}/logbro_Linux_arm64.tar.gz",
        verified: "github.com/lch88/logbro/",
        cookies: {
          "license" => "accept-backup",
        },
        header: [
          "X-Version: 0.1.0",
        ]
      sha256 "5cfde9ef9a1d9efe469f65efc7a13631ba81702a89809f6bd491b2c4cc5c3717"
    end
  end

  # No zap stanza required
end
